# Reference: https://artifacthub.io/packages/helm/bitnami/mongodb

configsvr:
  replicaCount: 1
  resourcesPreset: "none"

mongos:
  replicaCount: 1
  resourcesPreset: "none"

shardsvr:
  dataNode:
    replicaCount: 1
    resourcesPreset: "none"
  arbiter:
    replicaCount: 1
    resourcesPreset: "none"

# Including keys for:
# - mongodb-root-password: Admin password for user 'root'
# - mongodb-password: User password for customed user defined at 'auth.user'
# - mongodb-replica-set-key: Replication password for replication user
auth:
  existingSecret: "mongodb-sharded-password"

shards: 2

metrics:
  enabled: true
