# Reference: https://artifacthub.io/packages/helm/bitnami/mongodb-sharded/9.3.6

## NOTE: BREAKING MIGRATIONS
## Legacy Bitnami image
## Initiatives: https://news.broadcom.com/app-dev/broadcom-introduces-bitnami-secure-images-for-production-ready-containerized-applications
## Announement: https://github.com/bitnami/containers/issues/83267
global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/mongodb-sharded

configsvr:
  replicaCount: 1
  resourcesPreset: "none"

mongos:
  replicaCount: 1
  resourcesPreset: "none"

shardsvr:
  dataNode:
    replicaCount: 1
    resourcesPreset: "none"
  arbiter:
    replicaCount: 0
    resourcesPreset: "none"

# Including keys for:
# - mongodb-root-password: Admin password for user 'root'
# - mongodb-password: User password for customed user defined at 'auth.user'
# - mongodb-replica-set-key: Replication password for replication user
auth:
  existingSecret: "mongodb-sharded"

shards: 2

metrics:
  enabled: true
  image:
    repository: bitnamilegacy/mongodb-exporter
