apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-sharded
  namespace: argocd-apps
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: mongodb-sharded
      targetRevision: 9.3.6
      helm:
        valueFiles:
          - $values/argocd_values/mongodb-sharded/values.yaml
    - repoURL: "https://github.com/khangtictoc/ArgoCD-Apps.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb-sharded
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
