apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd-apps
  annotations:
    argocd.argoproj.io/ignore-resource-health: |
      networking.k8s.io/Ingress
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.46.0
      helm:
        valueFiles:
          - $values/argocd_values/loki/values.yaml
    - repoURL: "https://github.com/khangtictoc/ArgoCD-Apps.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
