apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth-arc-runners
  namespace: arc-runners
spec:
  namespace: admin
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: arc-runners
    serviceAccount: arc-runners
    audiences:
      - vault

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-arc-runners
  namespace: arc-runners
spec:
  namespace: admin
  refreshAfter: 30s

  type: kv-v2
  mount: aws
  path: k8s/oss/ci/github-action-runner-connector
  destination:
    name: arc-runners-creds
    create: true
  vaultAuthRef: static-auth-arc-runners
