apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd-apps
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.5.3
      helm:
        valueFiles:
          - $values/argocd_values/grafana-alloy/values.yaml
    - repoURL: "https://github.com/khangtictoc/ArgoCD-Apps.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-alloy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
