apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd-apps
spec:
  project: default
  sources:
    - repoURL: ghcr.io/nginx/charts
      chart: nginx-ingress
      targetRevision: 2.3.0
      helm:
        valueFiles:
          - $values/argocd_values/nginx/values.yaml
    - repoURL: "https://github.com/khangtictoc/ArgoCD-Apps.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
