# Reference: https://artifacthub.io/packages/helm/grafana/loki/6.46.0

# --- Basic Configurations (Enabled by default) ---

lokiCanary:
  replicas: 1

adminApi:
  replicas: 1

gateway:
  replicas: 1

write:
  replicas: 1

read:
  replicas: 1

backend:
  replicas: 1

ruler:
  replicas: 0

resultsCache:
  replicas: 1

chunksCache:
  replicas: 1
  l2:
    enabled: false
    replicas: 1

# --- Advanced Configurations (Disabled by default) ---

singleBinary:
  replicas: 0

ingester:
  replicas: 0

distributor:
  replicas: 0

querier:
  replicas: 0

queryFrontend:
  replicas: 0

queryScheduler:
  replicas: 0

indexGateway:
  replicas: 0

compactor:
  replicas: 0

bloomGateway:
  replicas: 0

bloomPlanner:
  replicas: 0

bloomBuilder:
  replicas: 0

patternIngester:
  replicas: 0

overridesExporter:
  replicas: 0

minio:
  replicas: 1
