# Reference: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
# Version: 11.1.1

configuration:
  # (Option 2) Backup Volumes as File System stored on S3 Bucket, not EC2 Snapshots -> If not used, please disabled
  defaultVolumesToFsBackup: true
  defaultBackupTTL: 876000h # 100 years -> Not to expire, Manual cleanup

  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero-backup-kubernetes-aws
      config:
        region: us-east-1

  # (Option 1) Only use if you want backup Persistent Volume as EC2 Snapshots. -> If not used, please disabled
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: us-east-1

# (Option 2) Enable Restic -> If not used, please disabled
deployNodeAgent: true

# AWS Authentication via Pod Identity
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    volumeMounts:
      - mountPath: /target
        name: plugins

serviceAccount:
  server:
    create: true
    name: velero-pod-identity

# Monitoring
metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s
