apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcp-vault
  namespace: argocd-apps
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.31.0
      helm:
        valueFiles:
          - $values/argocd_values/hcp-vault/values.yaml
    - repoURL: "https://github.com/khangtictoc/ArgoCD-Apps.git"
      targetRevision: main
      ref: values
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
  destination:
    server: https://kubernetes.default.svc
    namespace: hcp-vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
