# Reference: https://artifacthub.io/packages/helm/argo/argo-cd?modal=values

server:
  replicas: 1
  metrics:
    enabled: true
  ingress:
    enabled: false
    labels: {}
    annotations: {}
    ingressClassName: ""
    hostname: ""
    path: /
    tls: false

configs:
  params:
    application.namespaces: "argocd-apps" # "*" for wildcard, namespaces are separated by commas
  repositories:
    - url: https://github.com/khangtictoc/ArgoCD-Apps.git
      type: git
      name: ArgoCD-Apps

controller:
  replicas: 1
  metrics:
    enabled: true

repoServer:
  replicas: 1
  metrics:
    enabled: true

applicationSet:
  replicas: 1
  metrics:
    enabled: true

redis:
  metrics:
    enabled: true

notifications:
  enabled: true
  argocdUrl: ""
  metrics:
    enabled: true

commitServer:
  enabled: true
  metrics:
    enabled: true
