apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: postgresql
spec:
  namespace: admin
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: postgresql
    serviceAccount: postgresql
    audiences:
      - vault
